<?php

/**
 * Implements hook_theme().
 *
 * Shoehorns the checkout.js form into our Page.
 */
function donation_form_theme($existing, $type, $theme, $path) {
  return array(
    'stripe_form' => array(
      'variables' => array(
        'action'=> NULL,
        'anon_url' => NULL,
        'price' => NULL,
        'data' => NULL,
        'logged_in' => NULL,
        'entity_id' => NULL,
        'field_name' => NULL,
      ),
    ),
  );
}
